wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 2.11.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1659500161
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 53
      - 55
      4: 3.7.13
      5: 0.12.21
      6: 2.11.0
      8:
      - 5
